# Autogenerated from euler.yaml. Do not edit.

self: super:
let
  juspay-extra-src = super.eulerBuild.allowedPaths {
    root = ./..;
    paths = [
      ../src
      ../juspay-extra.cabal
    ];
  };

  
in 
super.eulerBuild.mkEulerHaskellOverlay self super
  (hself: hsuper: {
    
    
    juspay-extra = self.eulerBuild.fastBuild {
      drv = hself.callCabal2nix "juspay-extra" juspay-extra-src { };
      overrides = {
        # We want to run tests for our packages most of the time
        runTests = false;
      };
    };
  })
